"""
export_dt.py — inspect and export a trained DecisionTreeClassifier

Usage examples:

  # Print text summary of the tree
  python export_dt.py --model results/dt_run1_device0_d10.pkl --display text

  # Save a Graphviz dot file (render with: dot -Tpng tree.dot -o tree.png)
  python export_dt.py --model results/dt_run1_device0_d10.pkl --display dot --out tree.dot

  # Export as a self-contained Rust function (no_std compatible)
  python export_dt.py --model results/dt_run1_device0_d10.pkl --format rust --out src/dt_device0.rs

  # Export as JSON (portable intermediate, useful for writing your own interpreter)
  python export_dt.py --model results/dt_run1_device0_d10.pkl --format json --out dt_device0.json
"""

import argparse
import json
import pickle
import sys
import textwrap

import numpy as np
from sklearn.tree import export_text, export_graphviz

# ---------------------------------------------------------------------------
# Feature names (must match build_training_data in parse_and_train.py)
# ---------------------------------------------------------------------------
FEATURE_NAMES = (
    [f"prev{k}_lat_{d}" for k in [4, 3, 2, 1] for d in range(4)] +   # 16
    [f"prev{k}_out_{d}" for k in [4, 3, 2, 1] for d in range(3)] +   # 12
    [f"cur_out_{d}"     for d in range(3)]                             #  3
)  # total: 31

CLASS_NAMES = ["slow", "fast"]


# ---------------------------------------------------------------------------
# Display helpers
# ---------------------------------------------------------------------------

def display_text(model):
    print(export_text(model, feature_names=FEATURE_NAMES, max_depth=None))


def display_dot(model, out_path=None):
    dot = export_graphviz(
        model,
        feature_names=FEATURE_NAMES,
        class_names=CLASS_NAMES,
        filled=True,
        rounded=True,
        out_file=None,
    )
    if out_path:
        with open(out_path, "w") as f:
            f.write(dot)
        print(f"Dot file written to {out_path}")
        print(f"Render with:  dot -Tpng {out_path} -o tree.png")
    else:
        print(dot)


def print_stats(model):
    t = model.tree_
    print(f"  Nodes        : {t.node_count}")
    print(f"  Leaves       : {t.n_leaves}")
    print(f"  Max depth    : {model.get_depth()}")
    print(f"  n_features   : {model.n_features_in_}")
    print(f"  Classes      : {CLASS_NAMES}")


# ---------------------------------------------------------------------------
# JSON export
# ---------------------------------------------------------------------------

def to_json(model):
    t = model.tree_
    return {
        "n_features": int(model.n_features_in_),
        "feature_names": FEATURE_NAMES,
        "class_names": CLASS_NAMES,
        "children_left":  t.children_left.tolist(),
        "children_right": t.children_right.tolist(),
        "feature":        t.feature.tolist(),
        "threshold":      t.threshold.tolist(),
        "value":          t.value.tolist(),          # shape [n_nodes, 1, n_classes]
    }


# ---------------------------------------------------------------------------
# Rust export
# ---------------------------------------------------------------------------

TREE_LEAF = -1   # sklearn constant


def _rust_node(t, node, indent, lines):
    """Recursively emit Rust if/else for one node."""
    pad = "    " * indent

    if t.children_left[node] == TREE_LEAF:
        # Leaf: pick the class with the highest count
        counts = t.value[node][0]
        pred   = int(np.argmax(counts))
        lines.append(f"{pad}{pred}  // {CLASS_NAMES[pred]}  (counts: {counts.astype(int).tolist()})")
        return

    feat      = int(t.feature[node])
    threshold = t.threshold[node]
    # sklearn thresholds for integer features fall at X.5 — use integer comparison
    thresh_int = int(threshold)
    feat_name  = FEATURE_NAMES[feat]

    lines.append(f"{pad}if x[{feat}] <= {thresh_int} {{  // {feat_name} <= {threshold:.4f}")
    _rust_node(t, t.children_left[node],  indent + 1, lines)
    lines.append(f"{pad}}} else {{")
    _rust_node(t, t.children_right[node], indent + 1, lines)
    lines.append(f"{pad}}}")


def to_rust(model, fn_name="predict"):
    t = model.tree_
    lines = []

    lines.append("// Auto-generated by export_dt.py — do not edit by hand.")
    lines.append("//")
    lines.append(f"// Nodes : {t.node_count}")
    lines.append(f"// Leaves: {t.n_leaves}")
    lines.append(f"// Depth : {model.get_depth()}")
    lines.append("//")
    lines.append("// Feature layout (31 elements, all digits 0-9):")
    lines.append("//   x[0..16]  — previous 4 latency digits  (prev4_lat_0..prev1_lat_3)")
    lines.append("//   x[16..28] — previous 4 outstanding page digits")
    lines.append("//   x[28..31] — current outstanding page digits")
    lines.append("//")
    lines.append("// Returns: 0 = slow, 1 = fast")
    lines.append("")
    lines.append("#[inline]")
    lines.append(f"pub fn {fn_name}(x: &[u8; 31]) -> u8 {{")

    inner = []
    _rust_node(t, 0, indent=1, lines=inner)
    lines.extend(inner)

    lines.append("}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Inspect or export a trained DecisionTreeClassifier.")
    parser.add_argument("--model",   required=True, help="Path to .pkl model file")
    parser.add_argument("--display", choices=["text", "dot", "stats"], default=None,
                        help="Display mode: text (export_text), dot (graphviz), stats (summary)")
    parser.add_argument("--format",  choices=["rust", "json"], default=None,
                        help="Export format for deployment")
    parser.add_argument("--out",     default=None,
                        help="Output file path (stdout if omitted)")
    parser.add_argument("--fn_name", default="predict",
                        help="Rust function name (default: predict)")
    args = parser.parse_args()

    if args.display is None and args.format is None:
        parser.error("Specify at least one of --display or --format.")

    with open(args.model, "rb") as f:
        model = pickle.load(f)

    # ---- display ----
    if args.display == "stats":
        print_stats(model)
    elif args.display == "text":
        out = export_text(model, feature_names=FEATURE_NAMES, max_depth=None)
        if args.out:
            with open(args.out, "w") as f:
                f.write(out)
            print(f"Text tree written to {args.out}")
        else:
            print(out)
    elif args.display == "dot":
        display_dot(model, out_path=args.out if args.format is None else None)

    # ---- export ----
    if args.format == "json":
        content = json.dumps(to_json(model), indent=2)
        if args.out:
            with open(args.out, "w") as f:
                f.write(content)
            print(f"JSON written to {args.out}")
        else:
            print(content)

    elif args.format == "rust":
        content = to_rust(model, fn_name=args.fn_name)
        if args.out:
            with open(args.out, "w") as f:
                f.write(content)
            print(f"Rust source written to {args.out}")
        else:
            print(content)


if __name__ == "__main__":
    main()
