// SPDX-License-Identifier: MPL-2.0
use quote::{ToTokens, format_ident, quote, quote_spanned};
use syn::{FieldsNamed, ItemStruct, LitStr, Path, Token, spanned::Spanned};

use crate::parsing_utils::{generics_to_phantom, make_oqueues_field_name, path_to_turbofish};

/// The implementations of the `orpc_server` attr macro.
pub fn orpc_server_macro_impl(
    traits: syn::punctuated::Punctuated<Path, Token!(,)>,
    input: syn::ItemStruct,
) -> proc_macro2::TokenStream {
    let mut errors = Vec::new();

    let input_span = input.span();

    let ItemStruct {
        attrs,
        vis,
        struct_token,
        ident,
        generics,
        fields,
        semi_token,
    } = input;
    let (impl_generics, type_generics, where_clause) = generics.split_for_impl();

    // The fields holding the OQueues for each trait. These structs are generated by the `orpc_trait` macro.
    let oqueue_fields: Vec<_> = traits
        .iter()
        .map(|trait_ident| {
            let oqueue_field_ident = make_oqueues_field_name(&mut errors, trait_ident);
            let struct_ident = make_oqueues_struct_path(trait_ident);
            quote! {
                #[allow(unused)]
                #oqueue_field_ident: #struct_ident
            }
        })
        .collect();

    // The names of the OQueue fields.
    let oqueue_field_initializers: Vec<_> = traits
        .iter()
        .map(|i| {
            let field_name = make_oqueues_field_name(&mut errors, i);
            let struct_name = make_oqueues_struct_path(i);
            quote! { #field_name: #struct_name::new(path.clone()), }
        })
        .collect();

    let orpc_internal_struct_doc = LitStr::new(
        &format!("The ORPC internal data structure for {}", ident),
        input_span,
    );

    let orpc_internal_struct_ident = format_ident!("{}ORPCInternal", ident.to_string());

    // The initializer for the ORPC internals struct for this server type
    let internal_init = quote! {
        #orpc_internal_struct_ident {
            #(#oqueue_field_initializers)*
            base: ::ostd::orpc::framework::ServerBase::new(path, weak_this.clone()),
            _phantom: ::core::marker::PhantomData,
        }
    };

    // All the fields of the user declared server struct with the added orpc_internal field.
    let fields = match fields {
        syn::Fields::Named(FieldsNamed { named, .. }) => {
            let named = named.iter();
            quote! {
                {
                    #(#named,)*
                    #[doc(hidden)]
                    #[doc = "The internal ORPC framework data associated with this server."]
                    orpc_internal: #orpc_internal_struct_ident #type_generics
                }
            }
        }
        fs => {
            errors.push(quote_spanned! { fs.span() =>
                compile_error!("servers must have named fields")
            });
            fs.to_token_stream()
        }
    };

    // The implementation of `new_with` for this server.
    let new_with_impl = quote! {
        impl #impl_generics #ident #type_generics #where_clause {
            #[doc = "\
Create a new instance of Self constructed using `f`. `f` takes the ORPC internal data
for this server and a weak reference to `self` and should return an instance of the server.
For example,
```ignore
let server = Self::new_with(|orpc_internal, weak_this| Self {
    increment,
    atomic_count,
    orpc_internal,
})?;
```
"]
            #[track_caller]
            #vis fn new_with(
                path: ::ostd::orpc::path::Path,
                f: impl ::core::ops::FnOnce(#orpc_internal_struct_ident #type_generics, &::alloc::sync::Weak<Self>) -> Self,
            ) -> ::alloc::sync::Arc::<Self> {
                let server = ::alloc::sync::Arc::<Self>::new_cyclic(
                    move |weak_this| {
                        let orpc_internal = #internal_init;
                        f(orpc_internal, weak_this)
                    });
                server
            }
        }
    };

    let phantom = generics_to_phantom(&generics);

    let output = quote! {
        #(#attrs)*
        #vis
        #struct_token
        #ident
        #generics
        #fields
        #semi_token

        impl #impl_generics ::ostd::orpc::framework::Server for #ident #type_generics #where_clause {
            fn orpc_server_base(&self) -> &::ostd::orpc::framework::ServerBase {
                &self.orpc_internal.base
            }
        }

        #new_with_impl

        #[doc(hidden)]
        #[doc = #orpc_internal_struct_doc]
        #[allow(non_snake_case)]
        struct #orpc_internal_struct_ident #generics {
            base: ::ostd::orpc::framework::ServerBase,
            #(
                #oqueue_fields,
            )*
            _phantom: #phantom
        }

        #(#errors;)*
    };

    output
}

fn make_oqueues_struct_path(trait_ident: &Path) -> Path {
    let mut trait_ident = trait_ident.clone();
    if let Some(last_type_segment) = trait_ident.segments.last_mut() {
        last_type_segment.ident = format_ident!(
            "{}OQueues",
            last_type_segment.ident,
            span = last_type_segment.ident.span()
        );
    }
    path_to_turbofish(trait_ident)
}
