// SPDX-License-Identifier: MPL-2.0

/// Construct a new ORPC server (or just a cyclic `Arc` for the baseline).
///
/// This is a utility macro for constructing an ORPC server. It handles correctly calling the
/// `new_with` function generated by the `#[orpc_server]` macro. The expansion is straightforward,
/// but by using a macro we can change the internal fields used by ORPC servers and provide some
/// limited compatibility between ORPC and baseline builds.
///
/// ## Usage:
///
/// ```ignore
/// new_server!(|weak_self| {
///     ServerStruct {
///         ...fields...
///     }
/// })
/// ```
#[macro_export]
macro_rules! new_server {
    ($($args:tt)*) => {
        $crate::__new_server!($($args)*)
    };
}

/// See [`crate::new_server!`]
#[doc(hidden)]
#[macro_export]
#[cfg(not(baseline_asterinas))]
macro_rules! __new_server {
    // Pattern for structs with orpc_internal field
    (
        |$weak_self:tt| $struct_name:ident { $($field:ident $(:$value:expr)?),* $(,)? }
    ) => {
        $struct_name::new_with(|orpc_internal, $weak_self| $struct_name {
            orpc_internal,
            $($field $(:$value)?),*
        })
    };
}

/// See [`crate::new_server!`]
#[doc(hidden)]
#[macro_export]
#[cfg(baseline_asterinas)]
macro_rules! __new_server {
    // Pattern for structs with orpc_internal field
    (
        |$weak_self:tt| $struct_name:ident { $($field:ident $(:$value:expr)?),* $(,)? }
    ) => {
        Arc::new_cyclic(|$weak_self| $struct_name {
            $($field $(:$value)?),*
        })
    };
}
