// SPDX-License-Identifier: MPL-2.0

//! Utilities for serializating data.

use serde::Serialize;

/// A marker trait for structs which are serialized as tuple instead of a record. Its derive macro
/// generates a `Serialize` impl which serializes the type as a tuple. Members of the type will be
/// serialized using their normal `Serialize` impl, and so may serialize into any type.
///
/// See [`orpc_macros::TupleSerialize`] for more details.
///
/// This should not be used as a trait bound, like `T: TupleSerialize`. Instead, just use `T:
/// Serialize`. That guarantees that your code will work for any serializable `T`, even if it
/// doesn't use a tuple-serializer generated by the derive macro associated with this trait.
pub trait TupleSerialize: Serialize {}
