#!/usr/bin/env python3

import argparse
import subprocess
import os


def replace_string_in_file(f, src, dst):
    with open(f, "r", encoding="utf-8") as file:
        string = file.read()

    new_string = string.replace(src, dst)

    with open(f, "w", encoding="utf-8") as file:
        file.write(new_string)


def replace_version_strings(f, src_name, src_version, dest_name, dest_version):
    replace_string_in_file(
        f,
        f"{src_name}/asterinas:{src_version}",
        f"{dest_name}/asterinas:{dest_version}",
    )
    replace_string_in_file(
        f,
        f"{src_name}/osdk:{src_version}",
        f"{dest_name}/osdk:{dest_version}",
    )
    replace_string_in_file(
        f,
        f"{src_name}/nix:{src_version}",
        f"{dest_name}/nix:{dest_version}",
    )
    replace_string_in_file(
        f,
        f"{src_name}/kata:{src_version}",
        f"{dest_name}/kata:{dest_version}",
    )
    replace_string_in_file(f, f"{src_version}", f"{dest_version}")
    git_add(f)


# checks if there are modified or staged changes
# this doesn't look at untracked files, because those aren't lost during a hard reset
def has_uncommitted_changes():
    result = subprocess.run(["git", "diff", "--quiet", "HEAD"])
    return result.returncode != 0


def run_cmd(cmd):
    try:
        result = subprocess.run(
            cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(e.stdout)
        print(f"Error executing {' '.join(cmd)}: {e.stderr}")
        return None


def git_add(f):
    return run_cmd(["git", "add", f])


def git_commit(msg):
    return run_cmd(["git", "commit", "-m", msg])


# finds the commit hash of the commit with the specified message
def get_commit_hash(msg):
    log_string = run_cmd(["git", "log", "--oneline"])
    log = log_string.split("\n")

    for c in log:
        if msg in c:
            return c.split(" ")[0]


def delete_file(f):
    if os.path.exists(f):
        os.remove(f)
        print(f"Deleted {f}")
    else:
        print(f"{f} not found")


if __name__ == "__main__":
    DESCRIPTION = """\
        Helper for merging upstream asterinas into ldos fork.
        
        It temporarily rewrites ldos-specific image references + a github link
        to their upstream equivalents to avoid common merge conflicts, then
        restores them afterwards. The script is invoked twice to conduct a merge from
        upstream. The user invokes the script to start the merge, then resolves all merge conflicts,
        then invokes the script again to finish the merge. There is intermediate state that needs to be
        captured between the two invocations, the ldos image version (because DOCKER_IMAGE_VERSION
        often causes a merge conflict with upstream, so it must be overwritten) and the temporary commit hash
        automatically generated by the first invocation. The former is stored in DOCKER_IMAGE_VERSION_TEMP,
        while the latter isn't stored, and is instead found by parsing the git history for the commit message.
        After the merge conflicts are resolved and the user commits them, the user invokes the script again.
        The script will cherry pick the start commit to the top of the branch, then revert all version name changes,
        commit again, and then squash the two automated commits into the user's merge commit. This hides the commits
        made by the script, while also capturing any new upstream references to image versions.
    """

    EPILOG = """\
        Usage:
          1. python3 tools/merge_upstream.py --start    # rewrite refs, commit, then git merge upstream/main
          2. resolve any real merge conflicts and commit them
          3. python3 tools/merge_upstream.py --finish   # restore refs and squash into the merge commit
        
          python3 tools/merge_upstream.py --abort       # bail out and reset to before the merge
    """

    parser = argparse.ArgumentParser(
        prog="merge_upstream.py",
        description=DESCRIPTION,
        epilog=EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "-s",
        "--start",
        action="store_true",
        help="rewrite ldos image refs to upstream, commit, and start upstream merge",
    )
    parser.add_argument(
        "-f",
        "--finish",
        action="store_true",
        help="restore ldos image refs and squash this script's changes into the merge commit",
    )
    parser.add_argument(
        "-a",
        "--abort",
        action="store_true",
        help="abort the git merge and reset the working tree to before the merge",
    )
    args = parser.parse_args()

    if args.start:
        with open("DOCKER_IMAGE_VERSION", "r", encoding="utf-8") as file:
            ldos_version = file.readline().rstrip("\n")

        upstream_version = run_cmd(["git", "show", "upstream:DOCKER_IMAGE_VERSION"])

        print(f"ldos_version: {ldos_version}")
        print(f"upstream_version: {upstream_version}")

        out = run_cmd(["grep", "-rl", ldos_version, "."])
        files = out.split("\n")

        for f in files:
            replace_version_strings(
                f, "ldosproject", ldos_version, "asterinas", upstream_version
            )

        replace_string_in_file(
            ".github/actions/benchmark/action.yml",
            "github.com/ldos-project",
            "github.com/asterinas",
        )
        git_add(".github/actions/benchmark/action.yml")

        # save ldos_version for the finish stage (DOCKER_IMAGE_VERSION will be overwritten)
        with open("DOCKER_IMAGE_VERSION_TEMP", "w", encoding="utf-8") as file:
            file.write(ldos_version)
        print("Wrote DOCKER_IMAGE_VERSION_TEMP")

        out = git_commit("merge_upstream.py: merge start")
        print(out)

        # this will error if there are merge conflicts (but thats ok)
        run_cmd(["git", "merge", "upstream/main"])

    elif args.finish:
        # grab start commit hash
        commit_hash = get_commit_hash("merge_upstream.py: merge start")

        # delete start commit from git history
        out = run_cmd(["git", "rebase", "--onto", f"{commit_hash}^", commit_hash])
        print(out)

        # cherry-pick start commit back in
        out = run_cmd(["git", "cherry-pick", commit_hash])
        print(out)

        with open("DOCKER_IMAGE_VERSION_TEMP", "r", encoding="utf-8") as file:
            ldos_version = file.readline().rstrip("\n")
        with open("DOCKER_IMAGE_VERSION", "r", encoding="utf-8") as file:
            upstream_version = file.readline().rstrip("\n")

        print(f"ldos_version: {ldos_version}")
        print(f"upstream_version: {upstream_version}")

        out = run_cmd(["grep", "-rl", upstream_version, "."])
        files = out.split("\n")

        for f in files:
            replace_version_strings(
                f, "asterinas", upstream_version, "ldosproject", ldos_version
            )

        replace_string_in_file(
            ".github/actions/benchmark/action.yml",
            "github.com/asterinas",
            "github.com/ldos-project",
        )

        out = git_add(".github/actions/benchmark/action.yml")
        out = git_commit("merge_upstream.py: merge finish")
        print(out)

        delete_file("DOCKER_IMAGE_VERSION_TEMP")

        # git history is ordered as follows:
        #   merge_upstream.py finish commit
        #   merge_upstream.py start commit
        #   merge commit
        # top 2 commits will be squashed into the merge commit
        # to do this we soft reset to above the merge commit (so all the changes are staged), then commit all three at once

        msg = run_cmd(["git", "log", "--format=%B", "-1", "HEAD~2"])
        out = run_cmd(["git", "reset", "--soft", "HEAD~3"])
        print(out)
        out = git_commit(msg)
        print(out)

    elif args.abort:
        out = run_cmd(["git", "merge", "--abort"])
        print(out)

        delete_file("DOCKER_IMAGE_VERSION_TEMP")

        if has_uncommitted_changes():
            print("There are uncommitted changes, please run git stash before aborting")
        else:
            # resets back to above the merge_upstream.py start commit
            commit_hash = get_commit_hash("merge_upstream.py: merge start")

            out = run_cmd(["git", "reset", "--hard", f"{commit_hash}^"])
            print(out)

    else:
        print("Invalid argument!")
